<a href="https://colab.research.google.com/github/Samplergithub769/Data-Science-Intern/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [1]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [2]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1, 2, 3])




In [3]:
# print output

print(arr)

[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [4]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [5]:
#print dimentions of a,b, c and d
print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)
print("Dimension of c:", c.ndim)
print("Dimension of d:", d.ndim)




Dimension of a: 0
Dimension of b: 1
Dimension of c: 2
Dimension of d: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [6]:
# print shape of each a,b ,c and d
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)





Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [7]:
# print data type of c and d

print("Data type of c:", c.dtype)
print("Data type of d:", d.dtype)



Data type of c: int64
Data type of d: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [8]:
#print type of a and b variable

print("Type of a:", type(a))
print("Type of b:", type(b))




Type of a: <class 'numpy.ndarray'>
Type of b: <class 'numpy.ndarray'>


In [10]:
# Lets check length of array b, using len() function
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [12]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 =np.array([l1])
l4 =np.array([l2])



Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [13]:
#code here as instructed above
%timeit result = [a * b for a, b in zip(l1, l2)]



508 ns ± 8.63 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [14]:
l3 = np.array(l1)
l4 = np.array(l2)

# Use NumPy for element-wise multiplication
%timeit result = l3 * l4



538 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [15]:
#Create a numpy array using arange with 1 and 11 as parameter in it

arr1 = np.arange(1, 11)
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [16]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

arr2 = np.arange(1, 11, 2)
print(arr2)


[1 3 5 7 9]


In [17]:
# create numpy array using eye function with 3 as passed parameter

arr3 = np.eye(3)
print(arr3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [19]:
# Reshape x with 2 rows and 8 columns
x_reshaped = x.reshape(2, 8)

print(x_reshaped)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [20]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x_reshaped = x.reshape(2, 4, 2)

print(x_reshaped)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [23]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

x_reshaped = x.reshape(4, -1)

print(x_reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [24]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = x.reshape(2, 4, -1)  # Using -1 to automatically determine the last dimension

print(y)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [25]:
# Flattening y


y_flattened = y.flatten()  # Flattening y into a 1D array

print(y_flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [26]:
# Create an array a with all even numbers between 1 to 17

a = np.arange(2, 18, 2)
print(a)


[ 2  4  6  8 10 12 14 16]


In [27]:
# Get third element in array a
third_element = a[2]
print(third_element)

6


In [28]:
#Print 3rd, 5th, and 7th element in array a
elements = a[[2, 4, 6]]

print(elements)



[ 6 10 14]


Lets check the same for 2 D array

In [29]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# print the 3rd element from the 3rd row of a
third_element_third_row = a[2, 2]

print(third_element_third_row)


9


Well done!

Now lets check indexing for 3 D array

In [31]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

print(b)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.


Third_element = b[0, 1, 2]
print(third_element)

6


In [40]:
# Create 1D array

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80,90])




In [41]:
# Slice elements from 1st to 5th element from the following array:
sliced_arr = arr[0:5]
print(sliced_arr)




[10 20 30 40 50]


Note: The result includes the start index, but excludes the end index.



In [42]:
# Slice elements from index 5 to the end of the array:
sliced_arr = arr[5:]

print(sliced_arr)



[60 70 80 90]


In [43]:
# Slice elements from the beginning to index 5 (not included):

sliced_arr = arr[:5]  # Slicing from start to index 5 (exclusive)

print(sliced_arr)




[10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [45]:
# Print every other element from index 1 to index 7:
sliced_arr = arr[1:8:2]  # Slicing from index 1 to 7 with step 2

print(sliced_arr)



[20 40 60 80]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [46]:
# Return every other element from the entire array arr:
sliced_arr = arr[::2]

print(sliced_arr)



[10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [47]:
# Print array a
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
sliced_arr = a[2, 1:5]  # Selecting row index 2 and column indices 1 to 4 (not included)

print(sliced_arr)



[8 9]


In [49]:
# In array 'a' print index 2 from all the elements :
sliced_arr = a[:, 2]  # Select all rows and column index 2

print(sliced_arr)



[3 6 9]


In [50]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
sliced_arr = a[:, 1:]

print(sliced_arr)



[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [70]:
x1 = np.array([1, 2, 3, 4, 5])



In [71]:
# assign x2 = x1
x2 = x1




In [72]:
#print x1 and x2
print(x1)
print(x2)



[1 2 3 4 5]
[1 2 3 4 5]


Ok now you have seen that both of them are same

In [73]:
# change 1st element of x2 as 10

x2[0] = 10


In [74]:
#Again print x1 and x2

print("Original array (x1):", x1)
print("Assigned array (x2):", x2)


Original array (x1): [10  2  3  4  5]
Assigned array (x2): [10  2  3  4  5]


In [77]:
# Check memory share between x1 and x2
print(np.may_share_memory(x1, x2))

True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [80]:
# Create a view of x1 and store it in x3.

x1 = np.array([1, 2, 3, 4, 5])
x3 = x1.view()
print(x1)
print(x3)

[1 2 3 4 5]
[1 2 3 4 5]


In [81]:
# Again check memory share between x1 and x3

print(np.may_share_memory(x1, x3))


True


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [83]:
#Change 1st element of x3=100
x3[0] = 100



In [85]:
#print x1 and x3 to check if changes reflected in both
print("Original array (x1):", x1)
print("Viewed array (x3):", x3)



Original array (x1): [100   2   3   4   5]
Viewed array (x3): [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [86]:
# Now create an array x4 which is copy of x1
# x4=
x4 = x1.copy()  # Create an independent copy of x1
print("Original array (x1):", x1)
print("Copied array (x4):", x4)


Original array (x1): [100   2   3   4   5]
Copied array (x4): [100   2   3   4   5]


In [87]:
# Change the last element of x4 as 900

x4[-1] = 900  # Change the last element of x4





In [88]:
# print both x1 and x4 to check if changes reflected in both

print("Original array (x1):", x1)  # x1 remains unchanged
print("Copied array (x4):", x4)



Original array (x1): [100   2   3   4   5]
Copied array (x4): [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [89]:
#Check memory share between x1 and x4

print("Does x4 share memory with x1?", np.may_share_memory(x1, x4))


Does x4 share memory with x1? False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [90]:
# stack x1 and x4 along columns.

x1 = np.array([1, 2, 3, 4, 5])
x4 = np.array([10, 20, 30, 40, 900])

# Stack along columns
result = np.column_stack((x1, x4))

print("Stacked array along columns:")
print(result)


Stacked array along columns:
[[  1  10]
 [  2  20]
 [  3  30]
 [  4  40]
 [  5 900]]


In [91]:
#stack x1 and x4 along rows
result = np.vstack((x1, x4))

print("Stacked array along rows:")
print(result)


Stacked array along rows:
[[  1   2   3   4   5]
 [ 10  20  30  40 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [94]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1)
print(arr2)

# Join along rows (axis=0)
result = np.concatenate((arr1, arr2), axis=0)

print("Joined array along rows:")
print(result)




[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Joined array along rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [93]:
##join arr1 and arr2 along columns using concatenate() function

# Join along columns (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

print("Joined array along columns:")
print(result)

Joined array along columns:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [95]:
# append arr2 to arr1
# Append along rows (axis=0)
result = np.append(arr1, arr2, axis=0)

print("Appended array along rows:")
print(result)


Appended array along rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Lets use insert() function which Inserts values into array before specified index value

In [96]:
# Inserts values into array x1 before index 4 with elements of x4
# Define the arrays
x1 = np.array([1, 2, 3, 4, 5])
x4 = np.array([10, 20, 30])  # Elements to insert

# Insert x4 into x1 before index 4
result = np.insert(x1, 4, x4)

print("Array after insertion:")
print(result)


Array after insertion:
[ 1  2  3  4 10 20 30  5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [97]:
# delete 2nd element from array x2

x2 = np.array([10, 20, 30, 40, 50])

# Delete the 2nd element (index 1, since indexing starts at 0)
result = np.delete(x2, 1)

print("Array after deletion:")
print(result)


Array after deletion:
[10 30 40 50]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!