<a href="https://colab.research.google.com/github/Samplergithub769/Data-Science-Intern/blob/main/Python_Day_6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np #Import numpy library

In [37]:
A=np.array(5) #Scalar Array
A

array(5)

In [38]:
np.ndim(A) #Dimension Method

0

In [39]:
one=np.array([1,2,3,4,5])
one

array([1, 2, 3, 4, 5])

In [40]:
np.ndim(one)

1

In [41]:
Two=np.array([[1,2,3],[4,5,6]])
Two

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.ndim(Two)

2

In [43]:
Three=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
Three

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [44]:
np.ndim(Three)

3

List vs Numpy Array

In [45]:
list1=[1,4.0,"apple"] #List->Different Datatypes
arr=np.array([1,2,3,4,5])#Array->Same Datatypes

In [46]:
arr=np.array([1,2,3.9,"Apple"]) #Type conversion convert into string
print(arr)

['1' '2' '3.9' 'Apple']


In [47]:
type(arr)

numpy.ndarray

In [48]:
arr=np.array([1,2,3,4,5]) #Mathematical Opeartions
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

Array Consumes Less memory

array are faster than lists

Array Reshaping

In [49]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1D array to 2D array

In [50]:
newarr=arr.reshape(3,4)
newarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

1D array to 3D array

In [51]:
newarr=arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Array Indexing

In [52]:
arr=np.array([1,2,3,4,5])

In [53]:
arr[1]

2

In [54]:
arr[2]+arr[3]

7

In [57]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
arr[0,1]

2

In [59]:
arr[1,4]

10

In [60]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr[0,1,2] #0th matrix

6

In [64]:
arr[1,1,0] #1st matrix

10

Numpy Array Slicing

In [65]:
a1=np.array([1,2,3,4,5,6,7])
a1

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
a1[1:5]

array([2, 3, 4, 5])

In [67]:
a1[4:]

array([5, 6, 7])

In [68]:
a1[:4]

array([1, 2, 3, 4])

In [69]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [70]:
a2[1,1:4]

array([7, 8, 9])

In [71]:
a2[0:2,2]

array([3, 8])

In [72]:
a2[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [73]:
a3=np.array([[[10,11,12],[13,14,15],[16,17,18]],
             [[20,21,22],[23,24,25],[26,27,28]],
             [[30,31,32],[33,34,35],[36,37,38]]])
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [74]:
a3.shape

(3, 3, 3)

In [75]:
a3[:2,1:,:2] #[matrix:row:column]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])

View vs Copy

Copy is a new array and view is just a view of the original array

Any changes made to the copy will not affect the original array.

In [76]:
arr=np.array([1,2,3,4,5])
copy=arr.copy()
copy[0]=42
print(arr)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


Any changes made to the view will  affect the original array.

In [78]:
view=arr.view()
view[0]=42
print(arr)
print(copy)

[42  2  3  4  5]
[42  2  3  4  5]


Numpy Operations

In [85]:
a=np.array([[1,2,3],[4,5,6]]) #2D array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.append(a,[7,8,9]) #By default give 1D array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.append(a,[[7,8,9]],axis=0) #axis0->add as a row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.append(a,[[7],[8]],axis=1) #axis->1 as a column

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [92]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a=np.array([[1,2],
          [3,4],
          [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [98]:
np.insert(a,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [100]:
np.insert(a,1,[11,12,13],axis=1) #1 is a index

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [101]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
np.delete(b,6)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [105]:
np.delete(b,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [106]:
np.delete(b,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [107]:
np.ndim(b)

2

Hstack Vs Vstack

In [108]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [114]:
print(a,b)

[1 2 3] [4 5 6]


In [115]:
result=np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


In [116]:
np.ndim(result)

1

In [117]:
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [118]:
np.ndim(result)

2